name: Provider-Test
on: 
  workflow_dispatch:
    inputs:
      data:
        description: 'JSON object'
        required: true
jobs:
  DefaultExecution:
    name: Provider-Test
    runs-on: ubuntu-latest
    steps:
      - name: Run Script
        run: |
          echo "Hello World"
      - name: Inputs
        run: |
          echo "Inputs are as follows"
          echo '${{ github.event.inputs.data }}' | jq