name: Provider-Test
on: 
  workflow_dispatch:
jobs:
  DefaultExecution:
    name: Provider-Test
    runs-on: ubuntu-latest
    steps:
      - name: Run Script
        run: |
          echo "Hello World"